DROP TABLE IF EXISTS `OASIS_HEARTBEAT`;
CREATE TABLE `OASIS_HEARTBEAT` (
  `NODE_ID` varchar(32) NOT NULL,
  `LAST_UPDATE` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`NODE_ID`)
);


DROP TABLE IF EXISTS `OASIS_DATA`;
CREATE TABLE `OASIS_DATA` (
  `NODE_ID` VARCHAR(32) NOT NULL,
  `TIMESTAMP` VARCHAR(64) NOT NULL,
  `DATA` JSON NULL,
  PRIMARY KEY (`NODE_ID`, `TIMESTAMP`));

DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `USERNAME` varchar(8) NOT NULL,
  `PASSWORD` varchar(8) NOT NULL,
  PRIMARY KEY (`USERNAME`)
);

DROP TABLE IF EXISTS `OASIS_ANALYTIC`;
CREATE TABLE `OASIS_ANALYTIC` (
  `TIMESTAMP` varchar(64) NOT NULL,
  `NODE_ID` varchar(32) NOT NULL,
  `TYPE` varchar(16) NOT NULL,
  `DATA` json DEFAULT NULL,
  PRIMARY KEY (`TIMESTAMP`,`NODE_ID`)
);

DROP TABLE IF EXISTS `PRICES`;
CREATE TABLE `PRICES` (
  `SOURCE` VARCHAR(32) NOT NULL,
  `DATE` DATE NOT NULL,
  `DATA` JSON NULL,
  PRIMARY KEY (`SOURCE`, `DATE`));
