--
-- Table structure for table `DATA`
--
DROP TABLE IF EXISTS garden.DATA ;

CREATE TABLE garden.DATA (
  `ID` varchar(64) NOT NULL,
  `TIMESTAMP` varchar(64) NOT NULL,
  `STATUS_DHT` int(11) NOT NULL,
  `MEASURED_MOISTURE` decimal(8,4) DEFAULT NULL,
  `CALCULATE_TEMPERATURE` decimal(8,4) DEFAULT NULL,
  `MEASURED_TEMPERATURE` decimal(8,4) DEFAULT NULL,
  `MEASURED_HUMIDITY` decimal(8,4) DEFAULT NULL,
  `STATUS_FAN` tinyint(1) NOT NULL,
  `STATUS_LIGHT` tinyint(1) NOT NULL,
  `MEASURED_MOISTURE_A` tinyint(1),
  `MEASURED_MOISTURE_B` tinyint(1),
  `MEASURED_MOISTURE_C` tinyint(1)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
