CREATE TABLE "DATA" (
	`ID`	TEXT NOT NULL,
	`TIMESTAMP`	TEXT NOT NULL,
	`STATUS_DHT`	INTEGER NOT NULL,
	`MEASURED_MOISTURE`	NUMERIC,
	`CALCULATE_TEMPERATURE`	NUMERIC,
	`MEASURED_TEMPERATURE`	NUMERIC,
	`MEASURED_HUMIDITY`	INTEGER,
	`STATUS_FAN`	INTEGER NOT NULL,
	`STATUS_LIGHT`	INTEGER NOT NULL
)
CREATE TABLE "NODECFG" (
	`ID`	TEXT NOT NULL UNIQUE,
	`TEMPERATURE_THRESHOLD`	INTEGER DEFAULT 25,
	`MASK_CRON_LIGHT_ON`	TEXT NOT NULL DEFAULT '0 11 * * *',
	`MASK_CRON_LIGHT_OFF`	TEXT NOT NULL DEFAULT '0 20 * * *',
	`MASK_CRON_CTRL`	TEXT NOT NULL DEFAULT '*/2 * * * *',
	`LAST_UPDATE`	TEXT,
	PRIMARY KEY(ID)
)
