SKETCH = Oasis.ino

ESP_ROOT=$(BABILONIA_LIBS)/esp8266
ESP_LIBS=$(ESP_ROOT)/libraries

CUSTOM_LIBS =	$(BABILONIA_LIBS)/pubsubclient \
							$(BABILONIA_LIBS)/ArduinoJson/src

BUILD_EXTRA_FLAGS=-DMQTT_MAX_PACKET_SIZE=1024 -DSPIFFS_USE_MAGIC_LENGTH=0 -DSPIFFS_ALIGNED_OBJECT_INDEX_TABLES=1

#Board type
BOARD = nodemcuv2

FLASH_DEF=4M1M

ESP_PORT = 8266

UPLOAD_PORT = /dev/tty.wchusbserial1420

UPLOAD_SPEED = 115200

#VERBOSE = 0
